import {writeFile} from 'node:fs/promises';
const providers=[
 ['Civitai','真实出图：底模 + LoRA','Orchestration workflow / AIR，按 recipe 提交；验证图附强度与实际参数。视频仅核实 Wan v2.1 Civitai recipe，未实际生成视频。','https://developer.civitai.com/orchestration/recipes/'],
 ['Hugging Face','真实出图：Space + FLUX LoRA','区分 Hub 仓库、Space 和 Inference Providers。FLUX.1-dev + XLabs Realism LoRA 0.8 经 HF Router → fal-ai，512×512、12 steps、guidance 3.5、seed 42。执行前查询在线 provider mapping。','https://huggingface.co/docs/inference-providers/main/tasks/text-to-image'],
 ['Tensor.Art','TAMS 鉴权被拒绝','改用真实模型 ID、/v1/models/:id、/v1/jobs，验证 checkpoint / LoRA 类型和架构。现有两把 key 均返回 unauthorized / app not found。旧 OpenWorks 两张图仅是工具接口证据。当前经典 DIFFUSION Job 仅核实 SD1.5 / SDXL 等已列架构；其他架构明确报未核实。公共目录不是全量清单，可粘贴其他真实 ID。','https://github.com/Tensor-Art/tams-sdk.js'],
 ['Fal.ai','真实调用：计费受限','FLUX LoRA 返回 403 TOP_UP，归类计费限制。修正 model_name、尺寸、LoRA path/scale、num_images；Wan 用 num_frames / frames_per_second，不把秒数冒充帧数。flux-lora Input 未声明 negative_prompt，拒绝误传。','https://fal.ai/models/fal-ai/flux-lora/api'],
 ['ModelScope CN','真实调用：额度不足','正确 CN 域名、异步任务和 LoRA 格式。REST 示例不能证明本地 Diffusers kwargs 可用，宽高/seed/steps/CFG/negative 标记未核实并明确拒绝显式提交。Qwen Image Edit 的 image_url 按版本使用字符串/数组。','https://www.modelscope.cn/models/Tongyi-MAI/Z-Image-Turbo'],
 ['ModelScope AI','真实调用：额度 / 账户设置','使用 AI 域名，不与 CN Token 混用。一个 key 额度不足，一个需绑定阿里云账户。图像参数限制与 CN 相同；模型目录不等于开放在线推理权限。','https://www.modelscope.ai/models/Qwen/Qwen-Image-Edit-2511'],
 ['NanoGPT','真实调用：401 invalid_api_key','使用 /api/v1/images 与单模型 endpoints 能力元数据，校验实际尺寸、图像输入和输出张数。图片输入为 input_references；没有能力证据不启用 LoRA/seed。此 key 未完成出图验收。','https://docs.nano-gpt.com/api-reference/image-generation'],
 ['Agnes','文档与代码验证；无实测 key','修复视频错走图片接口、遗漏 size/ratio、硬编码尺寸；视频采用 /v1/videos 和官方参数，图片不假装支持 diffusion 参数/LoRA。','https://wiki.agnes-ai.com/en/docs/agnes-image-21-flash'],
 ['Gemini','文档与代码验证；无实测 key','按所选模型校验 imageConfig，停用已下线快捷模型；历史记录实际 SDK payload，不编造 seed、steps、CFG。','https://ai.google.dev/gemini-api/docs/image-generation'],
 ['SenseNova','文档与代码验证；无实测 key','只保留核实过的 SenseNova 6.8 chat 集成，删除错误标成商汤的模型与图像能力承诺。','https://github.com/OpenSenseNova/SenseNova6.8/blob/main/API.md'],
 ['OpenAI / Grok 兼容中转','文档与代码验证；无实测 key','使用用户显式配置的服务地址；修正 JSON 编辑输入及 Grok image 对象。兼容中转的实际覆盖以其响应为准，未自动替换供应商。','https://platform.openai.com/docs/api-reference/images'],
];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
await writeFile('public/verification/provider-audit.json',JSON.stringify({date:'2026-10-03',providers:providers.map(([provider,status,details,source])=>({provider,status,details,source})),scope:'Endpoint and parameter audit; generation evidence is limited to the exact requests in results.json. Browser click-through visual QA was not performed.'},null,2));
await writeFile('public/verification/provider-audit.html',`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>供应商接线审计 · ComfyCanvas</title><style>*{box-sizing:border-box}body{margin:0;background:#10141b;color:#e7edf5;font:16px/1.7 system-ui,sans-serif}main{max-width:1080px;margin:auto;padding:40px 24px}a{color:#67e8f9}h1{font-size:32px}h2{margin:0;font-size:20px}article{border:1px solid #334155;border-radius:16px;padding:24px;margin:16px 0;background:#1a202b}.status{color:#fde68a}p{color:#c4cddb}header p{max-width:850px}a:focus-visible{outline:2px solid #67e8f9;outline-offset:4px}</style><main><header><a href="/">← 工作室</a> · <a href="index.html">真实出图与工作流</a><h1>供应商接线审计</h1><p>2026-10-03 · 模型、端点、参数分别核对。已生成 6 张真实图片，其中 2 张是旧 OpenWorks 工具结果，不能计作 TAMS 模型 API 验收。欠费、账户设置、鉴权失败分别保留，未把拒绝响应写成成功。</p><p>界面已修复同供应商选模、LoRA 导入、目录请求竞态、参数填写与工作流恢复；新增的批量结果保存在历史记录。自动测试覆盖不代表全部模型都经过真实生成，未完成浏览器逐按钮视觉验收。</p></header>${providers.map(([name,status,detail,source])=>`<article><h2>${esc(name)}</h2><p class="status">${esc(status)}</p><p>${esc(detail)}</p><a href="${esc(source)}" target="_blank" rel="noopener noreferrer">官方依据 ↗</a></article>`).join('')}<p><a href="provider-audit.json" download>下载审计 JSON</a> · <a href="provider-audit-upstream.json" download>实际端点调用记录</a></p></main></html>`);
console.log('Provider audit report written');
